export const RUNTIME_CONFIG = {
  playerAcceleration: 1800,
  playerDeceleration: 2200,
  playerMaxSpeed: 320,
  playerJumpSpeed: 720,
  jumpReleaseMultiplier: 0.45,
  gravity: 1900,
  maxFallSpeed: 1100,
  coyoteTime: 0.1,
  jumpBuffer: 0.12,
  crouchHeightFactor: 0.58,
  cameraSmoothing: 0.12,
  collisionEpsilon: 0.01,
  groundProbeDistance: 0.5,
  maxMovementStep: 8,
  fixedStep: 1 / 60,
  maxPhysicsStepsPerFrame: 5,
  runThreshold: 220,
  idleThreshold: 5,
  attackDuration: 0.32,
  attackActiveStart: 0.08,
  attackActiveEnd: 0.2,
  attackCooldown: 0.18,
  attackReach: 34,
  attackHeightFactor: 0.55,
  damageInvulnerability: 0.75,
  knockbackSpeedX: 360,
  knockbackSpeedY: 420,
  deathDuration: 0.8,
  respawnInvulnerability: 0.5,
  playerModelScale: 1,
  playerModelOffsetX: 0,
  playerModelOffsetY: 0,
  playerModelOffsetZ: 0,
  playerModelFacingRightRotation: Math.PI / 2,
  playerModelFacingLeftRotation: -Math.PI / 2,
} as const;
